apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-demo
  labels:
    app: kubernetes-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-demo
  template:
    metadata:
      labels:
        app: kubernetes-demo
    spec:
      containers:
        - name: kubernetes-demo
          image: 177099687234.dkr.ecr.ap-south-1.amazonaws.com/kubernetes-demo:latest
          ports:
            - containerPort: 8080